# Домашнее задание к лекции "Функции"

Вам нужно помочь секретарю автоматизировать работу. Для этого нужно написать программу, которая будет на основе хранимых данных исполнять пользовательские команды.

Исходные данные имеют следующую структуру:

перечень всех документов
documents = [

 {'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'},
 
 {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'},
 
 {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'}
 
]
перечень полок, на которых хранятся документы (если документ есть в documents, то он обязательно должен быть и в directories)
directories = {

 '1': ['2207 876234', '11-2'],
 
 '2': ['10006'],
 
 '3': []
 
}

Общие требования к программе:

код должен быть грамотно декомпозирован (каждая функция отвечает за свою конкретную задачу, дублирующийся функционал переиспользуется, а его код не повторяется);
в коде отсутствуют глобальные переменные (за исключением documents и directories);
пользовательский ввод обрабатывается в цикле while до тех пор, пока пользователь явно не завершит программу (вводом команды "q").

### Задание 1¶

### Пункт 1. Пользователь по команде "p" может узнать владельца документа по его номеру

Примеры работы:

1.

Введите команду:
p

Введите номер документа:
10006

Результат:
Владелец документа: Аристарх Павлов

2.

Введите команду:
p

Введите номер документа:
12345

Результат:
Документ не найден в базе

In [1]:
# перечень всех документов
documents = [
 {'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'},
 {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'},
 {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'}
]

# перечень полок, на которых хранятся документы (если документ есть в documents, то он обязательно должен быть и в directories)
directories = {
 '1': ['2207 876234', '11-2'],
 '2': ['10006'],
 '3': []
}

In [2]:
print(documents)

[{'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'}, {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'}, {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'}]


In [3]:
print(directories)

{'1': ['2207 876234', '11-2'], '2': ['10006'], '3': []}


In [4]:
def document_owner(documents): # создаем функцию владелец_документа
    command_p = input("Введите номер документа: ")
    flag = True

    for i in documents:
        if i["number"] == command_p:
            print("Владелец документа: ", i["name"])
            flag = False

    if flag:
        print("Документ не найден в базе")
        
document_owner(documents)

Введите номер документа: 10006
Владелец документа:  Аристарх Павлов


In [5]:
def document_owner(documents): # создаем функцию владелец_документа
    command_p = input("Введите номер документа: ")

    for i in documents:
        if i["number"] == command_p:
            print("Владелец документа: ", i["name"])
            return
    else:
        print("Документ не найден в базе")
        return
       
document_owner(documents)

Введите номер документа: 12345
Документ не найден в базе


### Пункт 2. Пользователь по команде "s" может по номеру документа узнать на какой полке он хранится

Примеры работы:

1.

Введите команду:
s

Введите номер документа:
10006
Результат:
Документ хранится на полке: 2

2.

Введите команду:
p

Введите номер документа:
12345
Результат:
Документ не найден в базе

In [6]:
def doc_number(directories): # создаем функцию номер документа
    command_s = input("Введите номер документа: ")
    flag = True
    
    for i in directories:
        if command_s in directories[i]:
            print("Документ хранится на полке: ", i)
            flag = False
    if flag:
        print("Документ не найден в базе")
      
doc_number(directories)

Введите номер документа: 10006
Документ хранится на полке:  2


In [7]:
def doc_number(directories): # создаем функцию номер документа
    command_s = input("Введите номер документа: ")
    
    for i in directories:
        if command_s in directories[i]:
            print("Документ хранится на полке: ", i)
            return
    else:
        print("Документ не найден в базе")
        return
      
doc_number(directories)

Введите номер документа: 12345
Документ не найден в базе


### Пункт 3. Пользователь по команде "l" может увидеть полную информацию по всем документам

Пример работы:

Введите команду:

l

Результат:

№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1

№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1

№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2

In [8]:
def doc_info(documents, directories):  # создаем функцию информация по документам
    for i in documents:
        res = list(filter(lambda x: i["number"] in x[1], directories.items()))[0]
        type_ = i["type"]
        number = i["number"]
        name = i["name"]
        
        print("№: ", number, ", ", "тип: ", type_, ", ", "владелец: ", name, ", ", "полка хранения: ", res[0], sep = '')
       
        
doc_info(documents, directories)

№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2


### Пункт 4. Пользователь по команде "ads" может добавить новую полку

Примеры работы:

1.

Введите команду:
ads

Введите номер полки:
10

Результат:
Полка добавлена. Текущий перечень полок: 1, 2, 3, 10.

2.

Введите команду:
ads

Введите номер полки:
1

Результат:
Такая полка уже существует. Текущий перечень полок: 1, 2, 3.

In [9]:
def adding_a_shelf():  # создаем функцию добавление полки
    shelf = input("Введите номер полки: ")
    for i in directories.items():
        if shelf in i[0]:
            print(f"Такая полка уже существует. Текущий перечень полок: {list(directories.keys())}")
            break
    else:
        directories[shelf] = []
        print(f"Полка добавлена. Текущий перечень полок: {list(directories.keys())}")
        
adding_a_shelf()

Введите номер полки: 10
Полка добавлена. Текущий перечень полок: ['1', '2', '3', '10']


### Пункт 5. Пользователь по команде "ds" может удалить существующую полку из данных (только если она пустая)

Примеры работы:

1.

Введите команду:
ds

Введите номер полки:
3

Результат:
Полка удалена. Текущий перечень полок: 1, 2.

2.

Введите команду:
ds

Введите номер полки:
1

Результат:
На полке есть документа, удалите их перед удалением полки. Текущий перечень полок: 1, 2, 3.

3.

Введите команду:
ds

Введите номер полки:
4

Результат:
Такой полки не существует. Текущий перечень полок: 1, 2, 3.

In [13]:
def shelf_remove(directories): # создаем функцию удаления полки (если пустая)
    shelf = input("Введите номер полки: ")
    if shelf in directories.keys():
        for i in directories.items():
        
            if  i[1] == []:
                del directories[i[0]]
                print(f"Полка удалена. Текущий перечень полок: {list(directories.keys())}")
                break

            elif i[1] != []: 
                print(f"На полке есть документы, удалите их перед удалением полки. Текущий перечень полок: {list(directories.keys())}")
                break
            
    else:
        print(f"Такой полки не существует. Текущий перечень полок: {list(directories.keys())}")
   
    
shelf_remove(directories)

Введите номер полки: 3
На полке есть документы, удалите их перед удалением полки. Текущий перечень полок: ['1', '2', '3', '10']


In [18]:
directories.items()

dict_items([('1', ['2207 876234', '11-2']), ('2', ['10006']), ('3', []), ('10', [])])

In [14]:
command = 0

while command != "q":
    command = input("Введите команду: ")
    if command == "p":
        document_owner(documents)
    elif command == "s":
        doc_number(directories)
    elif command == "l":
        doc_info(documents, directories)
    elif command == "ads":
        adding_a_shelf()
    elif command == "ds":
        shelf_remove(directories)    

Введите команду: ds
Введите номер полки: 3
На полке есть документы, удалите их перед удалением полки. Текущий перечень полок: ['1', '2', '3', '10']
Введите команду: q
