# Домашнее задание к лекции "Функции"

Вам нужно помочь секретарю автоматизировать работу. Для этого нужно написать программу, которая будет на основе хранимых данных исполнять пользовательские команды.

Исходные данные имеют следующую структуру:

перечень всех документов
documents = [

 {'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'},
 
 {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'},
 
 {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'}
 
]
перечень полок, на которых хранятся документы (если документ есть в documents, то он обязательно должен быть и в directories)
directories = {

 '1': ['2207 876234', '11-2'],
 
 '2': ['10006'],
 
 '3': []
 
}

Общие требования к программе:

код должен быть грамотно декомпозирован (каждая функция отвечает за свою конкретную задачу, дублирующийся функционал переиспользуется, а его код не повторяется);
в коде отсутствуют глобальные переменные (за исключением documents и directories);
пользовательский ввод обрабатывается в цикле while до тех пор, пока пользователь явно не завершит программу (вводом команды "q").

### Задание 1¶

### Пункт 1. Пользователь по команде "p" может узнать владельца документа по его номеру

Примеры работы:

1.

Введите команду:
p

Введите номер документа:
10006

Результат:
Владелец документа: Аристарх Павлов

2.

Введите команду:
p

Введите номер документа:
12345

Результат:
Документ не найден в базе

In [1]:
# перечень всех документов
documents = [
 {'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'},
 {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'},
 {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'}
]

# перечень полок, на которых хранятся документы (если документ есть в documents, то он обязательно должен быть и в directories)
directories = {
 '1': ['2207 876234', '11-2'],
 '2': ['10006'],
 '3': []
}

In [5]:
print(documents)

[{'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'}, {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'}, {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'}]


In [4]:
print(directories)

{'1': ['2207 876234', '11-2'], '2': ['10006'], '3': []}


In [26]:
def document_owner(documents): # создаем функцию владелец_документа
    command_p = input("Введите номер документа: ")
    flag = True

    for i in documents:
        if i["number"] == command_p:
            print("Владелец документа: ", i["name"])
            flag = False

    if flag:
        print("Документ не найден в базе")
        
document_owner(documents)

Введите номер документа: 10006
Владелец документа:  Аристарх Павлов


### Пункт 2. Пользователь по команде "s" может по номеру документа узнать на какой полке он хранится

Примеры работы:

1.

Введите команду:
s

Введите номер документа:
10006
Результат:
Документ хранится на полке: 2

2.

Введите команду:
p

Введите номер документа:
12345
Результат:
Документ не найден в базе

In [33]:
def doc_number(directories): # создаем функцию номер документа
    command_s = input("Введите номер документа: ")
    flag = True
    
    for i in directories:
        if command_s in directories[i]:
            print("Документ хранится на полке: ", i)
            flag = False
    if flag:
        print("Документ не найден в базе")
      
doc_number(directories)

Введите номер документа: 10006
Документ хранится на полке:  2


### Пункт 3. Пользователь по команде "l" может увидеть полную информацию по всем документам

Пример работы:

Введите команду:

l

Результат:

№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1

№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1

№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2

In [ ]:
def doc_info(documents, directories):
    for i in documents:
        number = i["number"]
        type = i["type"]
        name = i["name"]
        storage_shelf = j

In [35]:
print(documents)

[{'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'}, {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'}, {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'}]


In [36]:
def l():
    for x in documents:
        type = x['type']
        number = x['number']
        name = x['name']
        print('{0}"{1}" "{2}"'.format(type, number, name))
        
l()

passport"2207 876234" "Василий Гупкин"
invoice"11-2" "Геннадий Покемонов"
insurance"10006" "Аристарх Павлов"
